
def get_dict(i_match, str_change=''):

    dict_csss = {   'ft':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > div > span.sc-bqWxrE.hVtlqB.currentScore > span',
                    'ft_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > div > span.sc-bqWxrE.hVtlqB.currentScore > span',
                    'ft_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > div > span.sc-bqWxrE.hVtlqB.currentScore > span',

                    'date':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > span',
                    'date_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > span',                                
                    'date_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > span',                                

                    'home':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.hXDsfD.fRddxb > div',
                    'home_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.hXDsfD.fRddxb > div',
                    'home_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.hXDsfD.fRddxb > div',

                    'q1_h':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q1_h_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q1_h_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',

                    'q2_h':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q2_h_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q2_h_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    
                    'q3_h':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q3_h_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q3_h_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScoref'',',
                    
                    'q4_h':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q4_h_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q4_h_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    
                    'total_h':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(1) > span.sc-bqWxrE.{str_change}.currentScore',
                    'total_h_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(1) > span.sc-bqWxrE.{str_change}.currentScore',
                    'total_h_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(1) > span.sc-bqWxrE.{str_change}.currentScore',
                    
                    'away':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fRddxb > div',
                    'away_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fRddxb > div',
                    'away_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fRddxb > div',
                    
                    'q1_a':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q1_a_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q1_a_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    
                    'q2_a':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q2_a_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q2_a_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    
                    'q3_a':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q3_a_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q3_a_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    
                    'q4_a':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q4_a_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    'q4_a_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                    
                    'total_a':   f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(2) > span.sc-bqWxrE.{str_change}.currentScore',
                    'total_a_2': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(2) > span.sc-bqWxrE.{str_change}.currentScore',
                    'total_a_3': f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(2) > span.sc-bqWxrE.{str_change}.currentScore',
                }
    
    return dict_csss


def store_css(key_rx, i_match, str_change=''):
    # Retornar el "value" de la key solicitada "key_rx"
    this_dict_csss = get_dict(i_match, str_change)
    return this_dict_csss[key_rx]












def get_list_keys(i_match):
    this_dict_csss = get_dict(i_match)

    # Lista con las keys del diccionario "this_dict_csss"
    list_keys_dict = list(this_dict_csss.keys())

    return list_keys_dict