
def get_key_value(css_temp, key_rx, i_match, str_change=''):
    
    dict_css_s = None

    if css_temp == 0:
        dict_css_s = {   
                        'ft':       f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > div > span.sc-bqWxrE.hVtlqB.currentScore > span',
                                      #__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-fqkvVR.sc-dcJsrY.gBgQbz.hNspbb.sc-836c558d-1.iOpidl > div.sc-fqkvVR.eeeBnr.sc-836c558d-2.blpTeR > div:nth-child(5) > div > div.sc-jlZhew.kgghii > div > div > div.sc-fqkvVR.kXwmsa > div > div.sc-fqkvVR.clkedU > div:nth-child({i_match}) > a > div > div > div.sc-fqkvVR.fEdaXl > div > span.sc-jEACwC.kUrmQh.currentScore > span
                        'date':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > span',
                                      #__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-fqkvVR.sc-dcJsrY.gBgQbz.hNspbb.sc-836c558d-1.iOpidl > div.sc-fqkvVR.eeeBnr.sc-836c558d-2.blpTeR > div:nth-child(5) > div > div.sc-jlZhew.kgghii > div > div > div.sc-fqkvVR.kXwmsa > div > div.sc-fqkvVR.clkedU > div:nth-child({i_match}) > a > div > div > div.sc-fqkvVR.fEdaXl > span
                        'home':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.hXDsfD.fRddxb > div',
                                      #__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-fqkvVR.sc-dcJsrY.gBgQbz.hNspbb.sc-836c558d-1.iOpidl > div.sc-fqkvVR.eeeBnr.sc-836c558d-2.blpTeR > div:nth-child(5) > div > div.sc-jlZhew.kgghii > div > div > div.sc-fqkvVR.kXwmsa > div > div.sc-fqkvVR.clkedU > div:nth-child({i_match}) > a > div > div > div.sc-fqkvVR.dOBKtv > div > div.sc-fqkvVR.kiamWz > div.sc-fqkvVR.sc-dcJsrY.ljIAAI.fFmCDf > div
                        'q1_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                                      #__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-fqkvVR.sc-dcJsrY.gBgQbz.hNspbb.sc-836c558d-1.iOpidl > div.sc-fqkvVR.eeeBnr.sc-836c558d-2.blpTeR > div:nth-child(5) > div > div.sc-jlZhew.kgghii > div > div > div.sc-fqkvVR.kXwmsa > div > div.sc-fqkvVR.clkedU > div:nth-child({i_match}) > a > div > div > div.sc-fqkvVR.dOBKtv > div > div.sc-fqkvVR.xceyz > div.sc-fqkvVR.sc-dcJsrY.fGPuHh.hNspbb > div:nth-child(1) > div > span.sc-jEACwC.koyIC.currentScore
                        'q2_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q3_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q4_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'total_h':  f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(1) > span.sc-bqWxrE.{str_change}.currentScore',
                        'away':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fRddxb > div',
                                      #__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-fqkvVR.sc-dcJsrY.gBgQbz.hNspbb.sc-836c558d-1.iOpidl > div.sc-fqkvVR.eeeBnr.sc-836c558d-2.blpTeR > div:nth-child(5) > div > div.sc-jlZhew.kgghii > div > div > div.sc-fqkvVR.kXwmsa > div > div.sc-fqkvVR.clkedU > div:nth-child({i_match}) > a > div > div > div.sc-fqkvVR.dOBKtv > div > div.sc-fqkvVR.kiamWz > div.sc-fqkvVR.sc-dcJsrY.gBgQbz.fFmCDf > div
                        'q1_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q2_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q3_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q4_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'total_a':  f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(2) > span.sc-bqWxrE.{str_change}.currentScore',
                    }  
                        
    elif css_temp == 1:
        dict_css_s = {   
                        'ft':       f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > div > span.sc-bqWxrE.hVtlqB.currentScore > span',
                        'date':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > span',                                
                        'home':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.hXDsfD.fRddxb > div',
                        'q1_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q2_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q3_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q4_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'total_h':  f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(1) > span.sc-bqWxrE.{str_change}.currentScore',
                        'away':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fRddxb > div',
                        'q1_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q2_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q3_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q4_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'total_a':  f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.gnEaMj > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(2) > span.sc-bqWxrE.{str_change}.currentScore',
                    }
                        
        
    elif css_temp == 2:
        dict_css_s = {   
                        'ft':       f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > div > span.sc-bqWxrE.hVtlqB.currentScore > span',
                        'date':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.iHLDa > span',                                
                        'home':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.hXDsfD.fRddxb > div',
                        'q1_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q2_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',                  
                        'q3_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q4_h':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.eHDZPm.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',                                   
                        'total_h':  f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(1) > span.sc-bqWxrE.{str_change}.currentScore',
                        'away':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.gdZIEA > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fRddxb > div',
                        'q1_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(1) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q2_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(2) > div > span.sc-bqWxrE.{str_change}.currentScore',
                        'q3_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(3) > div > span.sc-bqWxrE.{str_change}.currentScore',                   
                        'q4_a':     f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.cAiwkk > div.sc-hLBbgP.sc-eDvSVe.cGpNmx.fEHohf > div:nth-child(4) > div > span.sc-bqWxrE.{str_change}.currentScore',                                    
                        'total_a':  f'#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div:nth-child(1) > div.sc-hLBbgP.kxmCRE > div:nth-child({i_match}) > a > div > div > div.sc-hLBbgP.fVeOEc > div > div.sc-hLBbgP.sc-eDvSVe.cDnJFT.fTFJIj > div:nth-child(2) > span.sc-bqWxrE.{str_change}.currentScore',                    
                    }
        
    else:
        dict_css_s = {key_rx: None}
    
    return dict_css_s[key_rx]

def get_css_challenge_season():
    list_css_seasons = [
                            '94', '44230', '35348', '63922', '53250', '56494', '1408', '62731', '61498', '53250', '53374', '3376', '19960', 
                            '64269', '34372', '49241', '36657', '59546', '53727', '65026'
                        ]     
    
    return list_css_seasons



def get_css_button_previous():
    css_previous =  [
                        '#__next > main > div > div.fresnel-container.fresnel-greaterThanOrEqual-mdMin > div > div.sc-hLBbgP.sc-eDvSVe.gjJmZQ.fEHohf.sc-836c558d-1.eDNgWX > div.sc-hLBbgP.fSpQRs.sc-836c558d-2.kBACDz > div:nth-child(5) > div > div.sc-csuSiG.ikkoci > div > div > div.sc-hLBbgP.sYIUR > div > div.sc-hLBbgP.sc-eDvSVe.fcWLie.ilXvf > div:nth-child(1) > button',
                    ]
    
    return css_previous

# def store_css(css_temp, key_rx, i_match, str_change=''):
#    # Retornar el "value" de la key solicitada "key_rx"
#    this_dict_csss = get_dict(css_temp=css_temp, i_match=i_match, str_change=str_change)
#    return this_dict_csss[key_rx]



# def get_list_keys(i_match):
#    this_dict_csss = get_dict(i_match)
#
#    # Lista con las keys del diccionario "this_dict_csss"
#    list_keys_dict = list(this_dict_csss.keys())
#
#    return list_keys_dict