# Generated by Django 4.2.3 on 2023-07-29 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webscraping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="league",
            options={"managed": False},
        ),
    ]
