# Generated by Django 4.2.3 on 2023-07-29 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webscraping", "0002_alter_league_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="league",
            table="leagues",
        ),
    ]
