# Generated by Django 4.2.3 on 2023-07-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscraping", "0003_alter_league_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Links_leagues",
            fields=[
                (
                    "id_link",
                    models.IntegerField(
                        db_column="id_link", primary_key=True, serialize=False
                    ),
                ),
                (
                    "link_league",
                    models.CharField(db_column="link_league", max_length=150),
                ),
            ],
            options={
                "db_table": "links_leagues",
                "managed": False,
            },
        ),
    ]
